-- FPCourse.lean — library root; imports all 14 weekly modules (Weeks 0-12, 14)

import FPCourse.T01_ExpressionsFunctionsRecursion.W00_AlgebraicTypes
import FPCourse.T01_ExpressionsFunctionsRecursion.W01_ExpressionsTypesValues
import FPCourse.T01_ExpressionsFunctionsRecursion.W02_FunctionsSpecifications
import FPCourse.T01_ExpressionsFunctionsRecursion.W03_RecursionTermination

import FPCourse.T02_InductiveTypes.W04_AlgebraicDatatypes
import FPCourse.T02_InductiveTypes.W05_Lists
import FPCourse.T02_InductiveTypes.W06_Trees
import FPCourse.T02_InductiveTypes.W07_PolymorphismDecidability

import FPCourse.T03_HigherOrderAndSpecification.W08_HigherOrderFunctions
import FPCourse.T03_HigherOrderAndSpecification.W09_Specifications

import FPCourse.T04_SetsAndRelations.W10_SetsRelations

import FPCourse.T05_AbstractTypesAndTypeClasses.W11_AbstractTypes
import FPCourse.T05_AbstractTypesAndTypeClasses.W12_TypeClassesDecidable

import FPCourse.T06_StreamsAndCurryHoward.W14_CurryHoward
